/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{
	// 	type: 'autogenerated',
	// 	dirName: '.',
	// }],

	getStarted: [
		{
			type: 'autogenerated',
			dirName: 'get-started',
		},
  ],
	
	principles: [
		{
			type: 'autogenerated',
			dirName: 'principles',
		},
  ],
	
	tools: [
		{
			type: 'autogenerated',
			dirName: 'tools',
		},
		{
			type: 'link',
			label: 'WebAIM Contrast Checker', // The link label
			href: 'https://webaim.org/resources/contrastchecker/', // The external URL
		},
		{
      type: 'link',
      label: 'MDN ARIA Docs', // The link label
      href: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques', // The external URL
    },
  ],

	library: [
		{
			type: 'autogenerated',
			dirName: 'library',
		},
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
